services:
  - type: web
    name: rsshub
    env: node
    plan: free
    buildCommand: pnpm install
    startCommand: pnpm start
    rootDir: .
    envVars:
      - key: NODE_ENV
        value: production
      - key: PUPPETEER_SKIP_DOWNLOAD
        value: true

