services:
  - type: web
    name: rsshub
    env: node
    plan: free
    branch: main
    buildCommand: pnpm install && pnpm build
    startCommand: pnpm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: CACHE_TYPE
        value: memory
